### ISSUE TITLE
how can I contact you ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/Oxygenz-MapExtractor#1]
i need installation of ffmpeg on cloudlinux7  centos 7 for CB,

 i cannot for the life of me find a good place to get repo or ffmpeg that works..  i have tried a few installer but seems i am F**king it up somehow and now im stuck :(

I can pay you just let me know how much please

thanks

Spiro

**Comment by MacWarrior** [comment]
Hi, 
Please create an issue on my [Clipbucket fork](https://github.com/MacWarrior/clipbucket) instead of this unrelated project

Currently downloading centos 7 to test installation
